### ISSUE TITLE
Project not translated

### ISSUE THREAD

**Issue by sfederici** [leopard-js/leopard#162]
Project https://scratch.mit.edu/projects/807126457 cannot be translated.

I got this error message

`Cannot read properties of undefined (reading '0')
Leopard only supports new projects (created in Scratch 3.0). And the only supported extension is "pen"; all others will fail.`

The project is new and it just uses the pen extension.

**Comment by towerofnix** [comment]
The error message is misleading. This is the same error as encountered in https://github.com/leopard-js/sb-edit/issues/85, which I fixed recently in https://github.com/leopard-js/sb-edit/pull/89, though it's waiting on review from other maintainers.

There are other apparent issues: I can run the project without any errors, but once the thumbnail fades out, the stage screen is black! Sound works and I'm assuming the simulation does too (it makes engine noises when I press the button to fly and pause/unpause works), but the pen visuals are broken and I'm not sure why.

Here's a build of the project if you want to mess around with it: [twilight-flight.zip](https://github.com/leopard-js/leopard/files/10827509/twilight-flight.zip)

**Comment by sfederici** [comment]
> The error message is misleading. This is the same error as encountered in [leopard-js/sb-edit#85](https://github.com/leopard-js/sb-edit/issues/85), which I fixed recently in [leopard-js/sb-edit#89](https://github.com/leopard-js/sb-edit/pull/89), though it's waiting on review from other maintainers.

Now it translates. But the issue you mention is still present.
